name: Github Pages
on:
  push:
    tags: '*'
    branches: [ "main", "feature/docs" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip' # caching pip dependencies
    - name: Install
      run: |
        pip install sphinx
        pip install -q GitPython sphinx-rtd-theme breathe sphinx-sitemap sphinxcontrib-moderncmakedomain myst-parser pandoc-include sphinxcontrib-spelling 
    - name: Build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/